import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // GETTING STARTED Section
    {
      type: 'html',
      value: 'GETTING STARTED',
      className: 'sidebar-category-heading',
    },
    'welcome',
    'getting-started',
    'your-ai-toolkit',

    // MASTERING AI PROMPTS Section
    {
      type: 'html',
      value: 'MASTERING AI PROMPTS',
      className: 'sidebar-category-heading',
    },
    {
      type: 'category',
      label: 'Prompting',
      link: {
        type: 'generated-index',
        description: 'Learn how to write effective prompts for Claude and Gemini, with healthcare-specific templates and best practices.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'prompting',
        },
      ],
    },

    // CONTEXT & MEMORY Section
    {
      type: 'html',
      value: 'CONTEXT & MEMORY',
      className: 'sidebar-category-heading',
    },
    {
      type: 'category',
      label: 'Context Management',
      link: {
        type: 'generated-index',
        description: 'Set up persistent AI workspaces with Claude Projects and Gemini Gems to maintain context across sessions.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'context-and-memory',
        },
      ],
    },

    // RESEARCH & CONTENT CREATION Section
    {
      type: 'html',
      value: 'RESEARCH & CONTENT CREATION',
      className: 'sidebar-category-heading',
    },
    {
      type: 'category',
      label: 'Research & Content',
      link: {
        type: 'generated-index',
        description: 'Use AI for multi-source research, fact-checking, and creating presentations, dashboards, and documents.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'research-and-content',
        },
      ],
    },

    // WORKFLOW AUTOMATION Section
    {
      type: 'html',
      value: 'WORKFLOW AUTOMATION',
      className: 'sidebar-category-heading',
    },
    {
      type: 'category',
      label: 'Automation',
      link: {
        type: 'generated-index',
        description: 'Automate repetitive tasks with n8n, Zapier, MCP connections, and AI agents tailored to your function.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'automation',
        },
      ],
    },

    // GOVERNANCE & COMPLIANCE Section
    {
      type: 'html',
      value: 'GOVERNANCE & COMPLIANCE',
      className: 'sidebar-category-heading',
    },
    {
      type: 'category',
      label: 'Governance',
      link: {
        type: 'generated-index',
        description: 'Navigate PIPEDA, PHIPA, and HIPAA requirements for AI use in cross-border telehealth.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'governance',
        },
      ],
    },

    // LEADING AI ADOPTION Section
    {
      type: 'html',
      value: 'LEADING AI ADOPTION',
      className: 'sidebar-category-heading',
    },
    {
      type: 'category',
      label: 'Leadership',
      link: {
        type: 'generated-index',
        description: 'Measure AI ROI, drive organizational change, and define the executive role in AI adoption.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'leadership',
        },
      ],
    },

    // RESOURCES Section
    {
      type: 'html',
      value: 'RESOURCES',
      className: 'sidebar-category-heading',
    },
    'faq',
  ],
};

export default sidebars;
