import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // GETTING STARTED Section
    {
      type: 'html',
      value: 'GETTING STARTED',
      className: 'sidebar-category-heading',
    },
    'welcome',
    'getting-started',
    'your-ai-toolkit',

    // MASTERING AI PROMPTS Section
    {
      type: 'html',
      value: 'MASTERING AI PROMPTS',
      className: 'sidebar-category-heading',
    },
    {
      type: 'autogenerated',
      dirName: 'prompting',
    },

    // CONTEXT & MEMORY Section
    {
      type: 'html',
      value: 'CONTEXT & MEMORY',
      className: 'sidebar-category-heading',
    },
    {
      type: 'autogenerated',
      dirName: 'context-and-memory',
    },

    // RESEARCH & CONTENT CREATION Section
    {
      type: 'html',
      value: 'RESEARCH & CONTENT CREATION',
      className: 'sidebar-category-heading',
    },
    {
      type: 'autogenerated',
      dirName: 'research-and-content',
    },

    // WORKFLOW AUTOMATION Section
    {
      type: 'html',
      value: 'WORKFLOW AUTOMATION',
      className: 'sidebar-category-heading',
    },
    {
      type: 'autogenerated',
      dirName: 'automation',
    },

    // GOVERNANCE & COMPLIANCE Section
    {
      type: 'html',
      value: 'GOVERNANCE & COMPLIANCE',
      className: 'sidebar-category-heading',
    },
    {
      type: 'autogenerated',
      dirName: 'governance',
    },

    // LEADING AI ADOPTION Section
    {
      type: 'html',
      value: 'LEADING AI ADOPTION',
      className: 'sidebar-category-heading',
    },
    {
      type: 'autogenerated',
      dirName: 'leadership',
    },

    // RESOURCES Section
    {
      type: 'html',
      value: 'RESOURCES',
      className: 'sidebar-category-heading',
    },
    'faq',
  ],
};

export default sidebars;
